version: '3.9'

services:
  redis:
    container_name: penpot-redis
    image: redis:latest
    hostname: penpot-redis
    environment:
      TZ: Asia/Kuching
    volumes:
      - /data/penpot/redis:/data:rw
    restart: unless-stopped
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass redispass
    mem_limit: 256m
    mem_reservation: 50m
    cpu_shares: 768
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]

  db:
    image: postgres:latest
    container_name: penpot-db
    hostname: penpot-db
    environment:
      POSTGRES_DB: penpot
      POSTGRES_USER: penpotuser
      POSTGRES_PASSWORD: penpotpass
      POSTGRES_INITDB_ARGS: --data-checksums
    volumes:
      - /data/penpot/db:/var/lib/postgresql/data:rw
    restart: unless-stopped
    mem_limit: 512m
    cpu_shares: 768
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "penpot", "-U", "penpotuser"]
      timeout: 45s
      interval: 10s
      retries: 10

  penpot-exporter:
    container_name: penpot-exporter
    image: penpotapp/exporter:main
    hostname: penpot-exporter
    environment:
      - PENPOT_PUBLIC_URI=http://192.168.41.131
      - PENPOT_REDIS_URI=redis://:redispass@penpot-redis/0
    restart: unless-stopped
    mem_limit: 1g
    cpu_shares: 768

  penpot-backend:
    container_name: penpot-backend
    image: penpotapp/backend:main
    hostname: penpot-backend
    environment:
      PENPOT_FLAGS: enable-registration enable-login-with-password disable-email-verification enable-prepl-server enable-smtp
      PENPOT_SECRET_KEY: MariushostingMariushostingMari13
      ## The PREPL host. Mainly used for external programatic access to penpot backend
      ## (example: admin). By default it listen on `localhost` but if you are going to use
      ## the `admin`, you will need to uncomment this and set the host to `0.0.0.0`.
      # - PENPOT_PREPL_HOST=0.0.0.0
      PENPOT_PUBLIC_URI: http://192.168.41.131
      PENPOT_DATABASE_URI: postgresql://penpot-db/penpot
      PENPOT_DATABASE_USERNAME: penpotuser
      PENPOT_DATABASE_PASSWORD: penpotpass
      PENPOT_REDIS_URI: redis://:redispass@penpot-redis/0
      PENPOT_ASSETS_STORAGE_BACKEND: assets-fs
      PENPOT_STORAGE_ASSETS_FS_DIRECTORY: /opt/data/assets
      PENPOT_TELEMETRY_ENABLED: false
      PENPOT_SMTP_HOST: smtp.gmail.com
      PENPOT_SMTP_DEFAULT_FROM: Your-own-gmail-address
      PENPOT_SMTP_DEFAULT_REPLY_TO: Your-own-gmail-address
      PENPOT_SMTP_PORT: 587
      PENPOT_SMTP_USERNAME: howsenpl@gmail.com
      PENPOT_SMTP_PASSWORD: Your-own-app-password
      PENPOT_SMTP_TLS: true
      PENPOT_SMTP_SSL: false
    volumes:
      - /data/penpot/assets:/opt/data/assets:rw
    restart: unless-stopped
    mem_limit: 3g
    cpu_shares: 768
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy

  penpot-frontend:
    container_name: penpot-frontend
    image: penpotapp/frontend:main
    hostname: penpot-frontend
    environment:
      PENPOT_FLAGS: enable-registration enable-login-with-password
    volumes:
      - /data/penpot/assets:/opt/data/assets:rw
    ports:
      - 9010:80
    restart: unless-stopped
    mem_limit: 1g
    cpu_shares: 768
    depends_on:
      penpot-backend:
        condition: service_started
      penpot-exporter:
        condition: service_started

# http://localhost:9001